services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/venv
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - /app/build
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - backend
    restart: unless-stopped
    
  storybook:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "6006:6006"
    volumes:
      - ./frontend:/app
      - /app/build
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "storybook", "--", "--no-open"]
    restart: unless-stopped
